### ISSUE TITLE
Only Irish TV and Oireachtas TV are working 

### ISSUE THREAD

**Issue by scoobyciaran** [mathsgrinds/Kodi-Video-Plugin-Live-Irish-TV#21]
I have attached the log below. Thanks in advance:

20:14:34 T:18446744072314684784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('link',)
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.ietvnow/main.py", line 283, in <module>
                                                router(sys.argv[2])
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.ietvnow/main.py", line 266, in router
                                                play_item = xbmcgui.ListItem(path=params['link'])
                                            KeyError: ('link',)
                                            -->End of Python script error report<--
20:14:34 T:18446744072289832176   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ietvnow/?mode=play&link=]

**Comment by rlaphoenix** [comment]
Go into settings and set the prefered streams to Official Sites and see if that helps (You may need to restart kodi).
If not helpful let me know.
